name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI: 
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código fonte
        uses: actions/checkout@v3.5.3

      - name: Configurando Docker
        uses: docker/setup-docker@v2

      - name: Construindo a imagem Docker
        run: docker build -t fiapnoticiaapi:latest .

      - name: Logando no Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Enviando a imagem para o Docker Hub
        run: docker push <seu-nome-de-usuario-no-DockerHub>/fiapnoticiaapi:latest
