name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI: 
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código fonte
        uses: actions/checkout@v3.5.3

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.SERVERCONTAINERUSER }}
          password: ${{ secrets.CONTAINERREGISTRYPASSWORD }}
          login-server: ${{ secrets.SERVERCONTAINERREGISTRY }}
          
      - name: Azure Container Registry Build
        uses: Azure/acr-build@v1
        with:
          # Service Principal with Contributor role on the ACR
          service_principal: ${{ secrets.SP_ID }}
          # Service Principal password
          service_principal_password: ${{ secrets.SP_PASSWORD }}
          # Azure Container Registry tenant
          tenant: ${{ secrets.SP_TENTANT }}
          # The name of the ACR, minus the .azurecr.io
          registry: acrnoticiafiap
          # Repository to use
          repository: fiapnoticiaapi
          # Docker image tag, default to the commit SHA
          tag: latest
          # Branch to build from, defaults to master
          branch: main
      
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.SP_PASSWORD }}
          # ClientId of the Azure Service principal created.
          client-id: ${{ secrets.SP_ID }}
          # TenantId of the Azure Service principal created.
          tenant-id: ${{ secrets.SP_TENTANT }}
          # Azure subscriptionId
          subscription-id: ${{ secrets.SP_SUBSCRIPTION }}
      - name: Deploy to Azure Container Instances
        uses: Azure/aci-deploy@v1
        with:
          # Name of the Resource Group in which the Container Instance will be created
          resource-group: noticia-fiap
          command-line: dotnet Fiap.Noticias.API.dll 
          # Number of CPU Cores Required
          cpu: 1
          # The DNS Name Label for Container with Public IP
          dns-name-label: fiapnoticia
          gpu-count: 0
          # Specify the fully qualified container image name. For example, "myregistry.azurecr.io/nginx:latest" or "python:3.7.2-alpine/"
          image: acrnoticiafiap.azurecr.io/fiapnoticiaapi:latest
          # Location where the Container will be deployed
          location: East US
          memory: 1
          # Name of the Container Group Instance
          name: fiapnoticiaaci
          # The OS type of the Containers. Accepted Values are  { Linux, Windows }
          os-type: Linux
          ports: 80
          # The Network protocol to use. Accepted Values are { TCP, UDP }
          
